server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.170.12:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'